# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZGnZbjgjL98ba3AICuw0B0Jgtf_f4Kn5
"""

import sys
if 'google.colab' in sys.modules:
    import subprocess
    subprocess.call("pip install -U opencv-python".split())
from random import randrange
import matplotlib.pyplot as plt
import numpy as np
import cv2
from skimage import io
from google.colab.patches import cv2_imshow
figsize = (10, 10)
rgb_l = io.imread('https://img.mvideo.ru/Big/30058594bb2.jpg') 
rgb_r = io.imread('https://img.mvideo.ru/Big/30058594bb21.jpg')
gray_l = cv2.cvtColor(rgb_l, cv2.COLOR_RGB2GRAY)
gray_r = cv2.cvtColor(rgb_r, cv2.COLOR_RGB2GRAY)
cv2_imshow(rgb_l)
cv2_imshow(rgb_r)
cv2_imshow(gray_l)
cv2_imshow(gray_r)

feature_extractor = cv2.SIFT_create()


kp_l, desc_l = feature_extractor.detectAndCompute(gray_l, None)
kp_r, desc_r = feature_extractor.detectAndCompute(gray_r, None)

test = cv2.drawKeypoints(rgb_l, kp_l, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

plt.figure(figsize=figsize)
plt.imshow(test)
plt.title("keypoints")
plt.show()
match = cv2.BFMatcher()
matches = match.knnMatch(desc_l, desc_r, k=2)
good_matches = np.array([m1 for m1, m2 in matches if m1.distance < m2.distance / 3])

img_result = cv2.drawMatches(rgb_l, kp_l, rgb_r, kp_r, good_matches, None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)

plt.figure(figsize=(20, 20))
plt.imshow(img_result)
plt.title("keypoints matches")
plt.show()